import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
import { ThemeProvider } from "@/components/theme-provider"
import {NavBar} from "@/components/navbar";
import Image from "next/image";
import logo from "@/public/logo.svg"

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <>
            <html lang="en" suppressHydrationWarning>
            <head />
            <body suppressHydrationWarning>
            <ThemeProvider
                attribute="class"
                defaultTheme="system"
                enableSystem
                disableTransitionOnChange
            >
                <div className="flex flex-row justify-around fixed w-full p-6">
                    <div className="flex flex-row text-center justify-center">
                        <Image src={logo} alt={"logo"} height={80} />
                        Le Trèfle 2.0
                    </div>
                    <NavBar/>
                </div>
                {children}
            </ThemeProvider>
            </body>
            </html>
        </>
    )
}